In [1]:
import pickle
import numpy as np

In [2]:
with open('train_qa.txt','rb') as f:
    train_data = pickle.load(f)

In [3]:
with open('test_qa.txt','rb') as f:
    test_data = pickle.load(f)

In [4]:
type(train_data)

list

In [5]:
train_data[0]

(['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.'],
 ['Is', 'Sandra', 'in', 'the', 'hallway', '?'],
 'no')

In [6]:
' '.join(train_data[0][0])

'Mary moved to the bathroom . Sandra journeyed to the bedroom .'

In [7]:
data = train_data + test_data

In [8]:
vocab = set()

for story,question,answer in data:
    vocab = vocab.union(set(story))
    vocab = vocab.union(set(question))

In [9]:
vocab.add('no')

In [10]:
vocab.add('yes')

In [11]:
vocab

{'.',
 '?',
 'Daniel',
 'Is',
 'John',
 'Mary',
 'Sandra',
 'apple',
 'back',
 'bathroom',
 'bedroom',
 'discarded',
 'down',
 'dropped',
 'football',
 'garden',
 'got',
 'grabbed',
 'hallway',
 'in',
 'journeyed',
 'kitchen',
 'left',
 'milk',
 'moved',
 'no',
 'office',
 'picked',
 'put',
 'the',
 'there',
 'to',
 'took',
 'travelled',
 'up',
 'went',
 'yes'}

In [12]:
vocab_len = len(vocab) + 1

In [13]:
all_story_len = [len(d[0]) for d in data]
all_story_len

[12,
 26,
 39,
 52,
 64,
 12,
 24,
 36,
 49,
 61,
 13,
 25,
 38,
 50,
 63,
 13,
 25,
 37,
 49,
 61,
 24,
 37,
 48,
 71,
 83,
 13,
 25,
 37,
 50,
 62,
 12,
 24,
 35,
 46,
 71,
 12,
 24,
 37,
 50,
 62,
 13,
 25,
 38,
 50,
 62,
 12,
 24,
 36,
 48,
 60,
 13,
 25,
 39,
 50,
 62,
 13,
 26,
 38,
 49,
 60,
 12,
 24,
 36,
 49,
 61,
 13,
 26,
 39,
 51,
 62,
 13,
 25,
 38,
 52,
 65,
 12,
 24,
 37,
 48,
 61,
 13,
 25,
 38,
 51,
 64,
 12,
 25,
 39,
 53,
 65,
 12,
 24,
 36,
 48,
 60,
 12,
 24,
 36,
 49,
 61,
 12,
 25,
 38,
 50,
 61,
 25,
 37,
 49,
 60,
 72,
 13,
 25,
 36,
 48,
 60,
 12,
 24,
 36,
 48,
 60,
 12,
 23,
 36,
 47,
 59,
 12,
 24,
 35,
 48,
 61,
 12,
 23,
 36,
 49,
 62,
 12,
 25,
 37,
 48,
 59,
 12,
 25,
 37,
 49,
 60,
 12,
 24,
 36,
 49,
 61,
 12,
 25,
 37,
 49,
 61,
 12,
 24,
 37,
 49,
 60,
 12,
 25,
 38,
 50,
 61,
 12,
 24,
 36,
 49,
 61,
 12,
 24,
 35,
 48,
 61,
 12,
 25,
 37,
 49,
 62,
 12,
 24,
 38,
 50,
 62,
 12,
 25,
 38,
 50,
 62,
 12,
 24,
 36,
 48,
 60,
 12,
 24,
 36,
 49,
 60,


In [14]:
max_story_len = max(all_story_len)

In [15]:
max_ques_len = max([len(d[1]) for d in data])

In [16]:
from keras_preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer

In [17]:
tokenizer = Tokenizer(filters=[])
tokenizer.fit_on_texts(vocab)

In [18]:
tokenizer.word_index

{'to': 1,
 'bedroom': 2,
 'put': 3,
 'dropped': 4,
 '.': 5,
 'no': 6,
 'mary': 7,
 'hallway': 8,
 'football': 9,
 'apple': 10,
 'daniel': 11,
 'yes': 12,
 'sandra': 13,
 'travelled': 14,
 'kitchen': 15,
 'is': 16,
 'picked': 17,
 'there': 18,
 'up': 19,
 'journeyed': 20,
 'moved': 21,
 'took': 22,
 'bathroom': 23,
 'milk': 24,
 'garden': 25,
 'got': 26,
 'discarded': 27,
 '?': 28,
 'office': 29,
 'grabbed': 30,
 'the': 31,
 'left': 32,
 'down': 33,
 'john': 34,
 'went': 35,
 'in': 36,
 'back': 37}

In [19]:
train_story_text = []
train_questions_text = []
train_answers = []

In [20]:
for story,question,answer in train_data:
    train_story_text.append(story)
    train_questions_text.append(question)
    train_answers.append(answer)

In [21]:
train_story_text

[['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.'],
 ['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.',
  'Mary',
  'went',
  'back',
  'to',
  'the',
  'bedroom',
  '.',
  'Daniel',
  'went',
  'back',
  'to',
  'the',
  'hallway',
  '.'],
 ['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.',
  'Mary',
  'went',
  'back',
  'to',
  'the',
  'bedroom',
  '.',
  'Daniel',
  'went',
  'back',
  'to',
  'the',
  'hallway',
  '.',
  'Sandra',
  'went',
  'to',
  'the',
  'kitchen',
  '.',
  'Daniel',
  'went',
  'back',
  'to',
  'the',
  'bathroom',
  '.'],
 ['Mary',
  'moved',
  'to',
  'the',
  'bathroom',
  '.',
  'Sandra',
  'journeyed',
  'to',
  'the',
  'bedroom',
  '.',
  'Mary',
  'went',
  'back',
  'to',
  'the',
  'bedroom',
  '.',
  'Daniel',
  'went',
  'back',
  'to

In [22]:
train_story_seq = tokenizer.texts_to_sequences(train_story_text)

In [23]:
train_story_seq

[[7, 21, 1, 31, 23, 5, 13, 20, 1, 31, 2, 5],
 [7,
  21,
  1,
  31,
  23,
  5,
  13,
  20,
  1,
  31,
  2,
  5,
  7,
  35,
  37,
  1,
  31,
  2,
  5,
  11,
  35,
  37,
  1,
  31,
  8,
  5],
 [7,
  21,
  1,
  31,
  23,
  5,
  13,
  20,
  1,
  31,
  2,
  5,
  7,
  35,
  37,
  1,
  31,
  2,
  5,
  11,
  35,
  37,
  1,
  31,
  8,
  5,
  13,
  35,
  1,
  31,
  15,
  5,
  11,
  35,
  37,
  1,
  31,
  23,
  5],
 [7,
  21,
  1,
  31,
  23,
  5,
  13,
  20,
  1,
  31,
  2,
  5,
  7,
  35,
  37,
  1,
  31,
  2,
  5,
  11,
  35,
  37,
  1,
  31,
  8,
  5,
  13,
  35,
  1,
  31,
  15,
  5,
  11,
  35,
  37,
  1,
  31,
  23,
  5,
  11,
  17,
  19,
  31,
  9,
  18,
  5,
  11,
  35,
  1,
  31,
  2,
  5],
 [7,
  21,
  1,
  31,
  23,
  5,
  13,
  20,
  1,
  31,
  2,
  5,
  7,
  35,
  37,
  1,
  31,
  2,
  5,
  11,
  35,
  37,
  1,
  31,
  8,
  5,
  13,
  35,
  1,
  31,
  15,
  5,
  11,
  35,
  37,
  1,
  31,
  23,
  5,
  11,
  17,
  19,
  31,
  9,
  18,
  5,
  11,
  35,
  1,
  31,
  2,
  5,
  34,
  14,


In [24]:
def vectorize_stories(data,word_index=tokenizer.word_index,max_story_len=max_story_len,max_ques_len=max_ques_len):
    X = [] #stories = X
    Xq = [] #Questions
    Y = [] #Correct answer
    
    for story,ques,ans in data:
        x = [word_index[word.lower()] for word in story]
        xq = [word_index[word.lower()] for word in ques]
        y = np.zeros(len(word_index)+1)
        y[word_index[ans]] = 1
        
        X.append(x)
        Xq.append(xq)
        Y.append(y)
        
    return(pad_sequences(X,maxlen=max_story_len),pad_sequences(Xq,maxlen=max_ques_len),np.array(Y))

In [25]:
input_train,ques_train,ans_train = vectorize_stories(train_data)

In [26]:
input_test,ques_test,ans_test = vectorize_stories(test_data)

In [27]:
input_test

array([[ 0,  0,  0, ..., 31,  2,  5],
       [ 0,  0,  0, ..., 31, 25,  5],
       [ 0,  0,  0, ..., 31, 25,  5],
       ...,
       [ 0,  0,  0, ..., 31, 10,  5],
       [ 0,  0,  0, ..., 31, 25,  5],
       [ 0,  0,  0, ..., 10, 18,  5]])

In [28]:
ans_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [29]:
sum(ans_test)

array([  0.,   0.,   0.,   0.,   0.,   0., 503.,   0.,   0.,   0.,   0.,
         0., 497.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.])

In [30]:
from keras.models import Sequential, Model
from keras.layers import Input, Activation, Dense, Permute, Dropout,add, dot, concatenate, LSTM, Embedding

In [31]:
input_seq = Input((max_story_len,))
ques = Input((max_ques_len,))

In [32]:
vocab_size = len(vocab) + 1

In [33]:
#Input encoder M
input_encoder_m = Sequential()
input_encoder_m.add(Embedding(input_dim=vocab_size,output_dim=64))
input_encoder_m.add(Dropout(0.3))
# gives (samples,story_maxlen,embedding_dim)

In [34]:
#Input encoder C
input_encoder_c = Sequential()
input_encoder_c.add(Embedding(input_dim=vocab_size,output_dim=max_ques_len))
input_encoder_c.add(Dropout(0.3))
# gives (samples,story_maxlen,max_ques_len)

In [35]:
ques_encoder = Sequential()
ques_encoder.add(Embedding(input_dim=vocab_size,output_dim=64,input_length=max_ques_len))
ques_encoder.add(Dropout(0.3))
# gives (samples,max_ques_len,embedding_dim)

In [36]:
# encoded = encoder(input)
input_encoded_m = input_encoder_m(input_seq)
input_encoded_c = input_encoder_c(input_seq)
ques_encoded = ques_encoder(ques)

In [37]:
match = dot([input_encoded_m,ques_encoded],axes=(2,2))
match = Activation('softmax')(match)

In [38]:
response = add([match,input_encoded_c])
response = Permute((2,1))(response)

In [39]:
answer = concatenate([response,ques_encoded])
answer

<KerasTensor: shape=(None, 6, 220) dtype=float32 (created by layer 'concatenate')>

In [40]:
answer = LSTM(32)(answer)
answer = Dropout(0.5)(answer)
answer = Dense(vocab_size)(answer)
# gives (samples,vocab_size) YES/NO 0000 

In [41]:
answer = Activation('softmax')(answer)

In [42]:
model = Model([input_seq,ques],answer)

In [43]:
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

In [44]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 156)]        0           []                               
                                                                                                  
 input_2 (InputLayer)           [(None, 6)]          0           []                               
                                                                                                  
 sequential (Sequential)        (None, None, 64)     2432        ['input_1[0][0]']                
                                                                                                  
 sequential_2 (Sequential)      (None, 6, 64)        2432        ['input_2[0][0]']                
                                                                                              

In [45]:
history = model.fit([input_train,ques_train],ans_train,batch_size=32,epochs=100,validation_data=([input_test,ques_test],ans_test))

Epoch 1/100
313/313 [==============================] - 11s 19ms/step - loss: 0.8915 - accuracy: 0.4942 - val_loss: 0.6943 - val_accuracy: 0.4970
Epoch 2/100
313/313 [==============================] - 4s 12ms/step - loss: 0.7021 - accuracy: 0.5045 - val_loss: 0.6959 - val_accuracy: 0.5030
Epoch 3/100
313/313 [==============================] - 4s 13ms/step - loss: 0.6965 - accuracy: 0.4975 - val_loss: 0.6934 - val_accuracy: 0.5030
Epoch 4/100
313/313 [==============================] - 4s 14ms/step - loss: 0.6957 - accuracy: 0.4952 - val_loss: 0.6935 - val_accuracy: 0.5030
Epoch 5/100
313/313 [==============================] - 5s 16ms/step - loss: 0.6948 - accuracy: 0.5015 - val_loss: 0.6935 - val_accuracy: 0.5030
Epoch 6/100
313/313 [==============================] - 5s 15ms/step - loss: 0.6947 - accuracy: 0.4990 - val_loss: 0.6946 - val_accuracy: 0.4970
Epoch 7/100
313/313 [==============================] - 4s 14ms/step - loss: 0.6948 - accuracy: 0.4997 - val_loss: 0.6935 - val_accuracy

313/313 [==============================] - 4s 13ms/step - loss: 0.2870 - accuracy: 0.8753 - val_loss: 0.3433 - val_accuracy: 0.8440
Epoch 58/100
313/313 [==============================] - 4s 14ms/step - loss: 0.2859 - accuracy: 0.8719 - val_loss: 0.3691 - val_accuracy: 0.8330
Epoch 59/100
313/313 [==============================] - 4s 14ms/step - loss: 0.2802 - accuracy: 0.8764 - val_loss: 0.3666 - val_accuracy: 0.8350
Epoch 60/100
313/313 [==============================] - 4s 14ms/step - loss: 0.2789 - accuracy: 0.8756 - val_loss: 0.3460 - val_accuracy: 0.8410
Epoch 61/100
313/313 [==============================] - 4s 14ms/step - loss: 0.2767 - accuracy: 0.8773 - val_loss: 0.3708 - val_accuracy: 0.8320
Epoch 62/100
313/313 [==============================] - 4s 14ms/step - loss: 0.2805 - accuracy: 0.8757 - val_loss: 0.3603 - val_accuracy: 0.8300
Epoch 63/100
313/313 [==============================] - 5s 17ms/step - loss: 0.2781 - accuracy: 0.8774 - val_loss: 0.3508 - val_accuracy: 0.837

In [46]:
filename = 'chatbot_120_epochs.h5'
model.save(filename)

In [48]:
pred_results = model.predict(([input_test,ques_test]))

32/32 [==============================] - 0s 4ms/step


In [49]:
pred_results.shape

(1000, 38)

In [50]:
pred_results

array([[1.8419445e-11, 1.7520799e-11, 1.5994791e-11, ..., 1.9058885e-11,
        1.6480567e-11, 1.5215657e-11],
       [2.6781012e-12, 2.6596839e-12, 2.4946848e-12, ..., 2.8377496e-12,
        2.4654469e-12, 2.4581593e-12],
       [9.1494392e-14, 8.4475761e-14, 9.5963981e-14, ..., 9.8517033e-14,
        9.0573965e-14, 9.9140023e-14],
       ...,
       [1.9098979e-11, 1.9098324e-11, 1.8485255e-11, ..., 2.2293136e-11,
        1.6840971e-11, 1.7938612e-11],
       [2.9030201e-12, 3.2582619e-12, 2.9411027e-12, ..., 2.8252281e-12,
        3.2365647e-12, 2.8462354e-12],
       [9.2533349e-11, 9.5327288e-11, 8.2345457e-11, ..., 6.9278111e-11,
        8.2643156e-11, 8.8272029e-11]], dtype=float32)

In [51]:
test_data[0][1]

['Is', 'John', 'in', 'the', 'kitchen', '?']

In [52]:
test_data[0][2]

'no'

In [53]:
val_max = np.argmax(pred_results[0])

In [54]:
for key,val in tokenizer.word_index.items():
    if val == val_max:
        k = key

In [55]:
k

'no'

In [56]:
pred_results[0][val_max]

0.9999686

In [57]:
vocab

{'.',
 '?',
 'Daniel',
 'Is',
 'John',
 'Mary',
 'Sandra',
 'apple',
 'back',
 'bathroom',
 'bedroom',
 'discarded',
 'down',
 'dropped',
 'football',
 'garden',
 'got',
 'grabbed',
 'hallway',
 'in',
 'journeyed',
 'kitchen',
 'left',
 'milk',
 'moved',
 'no',
 'office',
 'picked',
 'put',
 'the',
 'there',
 'to',
 'took',
 'travelled',
 'up',
 'went',
 'yes'}

In [58]:
story = "John left the kitchen . Sandra dropped the football in the garden ."
story.split()

['John',
 'left',
 'the',
 'kitchen',
 '.',
 'Sandra',
 'dropped',
 'the',
 'football',
 'in',
 'the',
 'garden',
 '.']

In [59]:
question = "Is the football in the garden ?"
question.split()

['Is', 'the', 'football', 'in', 'the', 'garden', '?']

In [61]:
mydata = [(story.split(),question.split(),'yes')]

In [62]:
my_story,my_ques,my_ans = vectorize_stories(mydata)

In [66]:
my_ans

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.]])

In [67]:
pred_results = model.predict(([ my_story, my_ques]))

1/1 [==============================] - 0s 47ms/step


In [68]:
val_max = np.argmax(pred_results[0])

for key, val in tokenizer.word_index.items():
    if val == val_max:
        k = key

print("Predicted answer is: ", k)
print("Probability of certainty was: ", pred_results[0][val_max])

Predicted answer is:  yes
Probability of certainty was:  0.99992573
